version: "3"
services:
  redis-server:
    image: "redis"

  influxdb:
    image: influxdb:2.0
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpassword
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_BUCKET=my-bucket
      - DOCKER_INFLUXDB_INIT_RETENTION=1w
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-auth-token
    # volumes:
    #   - influxdb_data:/var/lib/influxdb2
    depends_on:
      - redis-server

  kafka1:
    image: confluentinc/cp-kafka
    container_name: kafka1
    hostname: kafka1
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_LISTENERS: "INTERNAL://kafka1:29092,CONTROLLER://kafka1:29093,EXTERNAL://0.0.0.0:9092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka1:29092,EXTERNAL://localhost:9092"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka1:29093"
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      CLUSTER_ID: "ciWo7IWazngRchmPES6q5A=="
      KAFKA_LOG_DIRS: "/tmp/kraft-combined-logs"
    depends_on:
      - influxdb

  publisher1:
    container_name: publisher1
    build:
      context: ../../../publisher
      dockerfile: Dockerfile
    depends_on:
      - kafka1
    environment:
      - KF_HOST=kafka1
      - KF_PORT=29092
      - KF_TOPIC=stock-market1
    command: sh -c "sleep 30 && node publisher1.js"

  publisher2:
    container_name: publisher2
    build:
      context: ../../../publisher
      dockerfile: Dockerfile
    depends_on:
      - kafka1
    environment:
      - KF_HOST=kafka1
      - KF_PORT=29092
      - KF_TOPIC=stock-market1
    command: sh -c "sleep 30 && node publisher1.js"

  # consumer-rust-1:
  #   container_name: consumer-rust-1
  #   build:
  #     context: ../../../consumer/rust
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - kafka1
  #     - publisher2
  #   environment:
  #     - KF_HOST=kafka1
  #     - KF_PORT=29092
  #     - KF_TOPIC=stock-market1
  #     - REDIS_URL=redis://redis-server:6379
  #   command: sh -c "sleep 40 && kafka-rust"

  # consumer-node-1:
  #   container_name: consumer-node-1
  #   build:
  #     context: ../../../consumer/node
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - kafka1
  #     - publisher2
  #   environment:
  #     - KF_HOST=kafka1
  #     - KF_PORT=29092
  #     - KF_TOPIC=stock-market1
  #   command: sh -c "sleep 40 && node consumer1.js"

  consumer-python-1:
    container_name: consumer-python-1
    build:
      context: ../../../consumer/python
      dockerfile: Dockerfile
    depends_on:
      - kafka1
      - publisher2
    environment:
      - KF_HOST=kafka1
      - KF_PORT=29092
      - KF_TOPIC=stock-market1
    command: sh -c "sleep 40 && python consumer1.py"
